### ISSUE TITLE
Doorstop crashes on asset filename conflict

### ISSUE THREAD

**Issue by blastur** [jacebrowning/doorstop#245]
Since #239 was merged, I can no longer provide my own CSS styling. I'm not sure if this is a bug or intended behavior, but what I used to do was to run ```doorstop publish``` and let it use the default template, which in turn references bootstrap.min.css and the sidebar CSS. Because these files were not provided, I assumed I should provide them myself, so I created an assets/ subfolder below my document and put the files in there. Doorstop automatically copied my provided asset-folder into the published directory, so I assumed I did something right :)

When I use the latest doorstop, an error occurs during publish:
```
$ doorstop publish all ./html
building tree...
loading documents...
publishing tree to '/home/mago/dev/myreqs/html'...
Traceback (most recent call last):
  File "/home/mago/doorstep/bin/doorstop", line 11, in <module>
    load_entry_point('Doorstop==1.2.1', 'console_scripts', 'doorstop')()
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/cli/main.py", line 104, in main
    success = function(args, os.getcwd(), parser.error)
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/cli/commands.py", line 504, in run_publish
    template=args.template, **kwargs)
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/core/publisher.py", line 83, in publish
    if obj2.copy_assets(assets_dir):
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/core/document.py", line 215, in copy_assets
    common.copy_dir_contents(self.assets, dest)
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/common.py", line 188, in copy_dir_contents
    shutil.copytree(fpath, dest_path)
  File "/home/mago/doorstep/lib/python3.5/shutil.py", line 309, in copytree
    os.makedirs(dst)
  File "/home/mago/doorstep/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/mago/dev/myreqs/html/assets/_css'
```

The thing in Doorstop that copies the default assets should probably skip files if such file already exists. This would allow one to put in custom CSSs, if you want cute sidebar styling for example.

Steps to reproduce:
```
$ mkdir asdf
$ cd asdf
$ git init
$ doorstop create ABC .
building tree...
created document: ABC (@/.)
$ doorstop add ABC -c2
building tree...
added item: ABC001 (@/ABC001.yml)
added item: ABC002 (@/ABC002.yml)
$ mkdir -p assets/_css/
$ touch assets/_css/sidebar.css
$ doorstop publish all ./html
building tree...
loading documents...
publishing tree to '/home/mago/asdf/html'...
Traceback (most recent call last):
  File "/home/mago/doorstep/bin/doorstop", line 11, in <module>
    load_entry_point('Doorstop==1.2.1', 'console_scripts', 'doorstop')()
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/cli/main.py", line 104, in main
    success = function(args, os.getcwd(), parser.error)
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/cli/commands.py", line 504, in run_publish
    template=args.template, **kwargs)
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/core/publisher.py", line 83, in publish
    if obj2.copy_assets(assets_dir):
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/core/document.py", line 215, in copy_assets
    common.copy_dir_contents(self.assets, dest)
  File "/home/mago/doorstep/lib/python3.5/site-packages/doorstop/common.py", line 188, in copy_dir_contents
    shutil.copytree(fpath, dest_path)
  File "/home/mago/doorstep/lib/python3.5/shutil.py", line 309, in copytree
    os.makedirs(dst)
  File "/home/mago/doorstep/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/mago/asdf/html/assets/_css'
```

Expected behaviour: My local sidebar.css should be used in the published document.
Actual behaviour: Doorstop can't handle conflicts in asset filenames.

**Comment by jacebrowning** [comment]
@michaelnt Any thoughts on how to handle this?

**Comment by michaelnt** [comment]
I had a similar problem at work today where two documents contained folders with the same name. I think the error message should be improved but I don't think there is anything more that can be done. Not copying the folder doesn't really help.

I think you should edit your template so that it doesn't use the same folder name as the default template. Calling the folders _css and _js was an attempt to avoid clashes, perhaps some other name would make it clearer, e.g. doorstop_css and doorstop_js?

If it is really a problem the default doorstop template could template the location of the assets, e.g.

`<link type="text/css" rel="stylesheet" href="assets/$dir/sidebar.css">`

**Comment by jacebrowning** [comment]
How about nesting the default assets in a `doorstop` subdirectory: `doorstop/css` and `doorstop/js`?
